wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.3
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.6
batch_size:
  desc: null
  value: 16
dataset:
  desc: null
  value: YahooFinance
learning_rate:
  desc: null
  value: 0.001
